steps:
  - name: gradle:jdk8
    entrypoint: gradle
    args: ["test"]
  - name: gradle:jdk8
    entrypoint: gradle
    args: ["assemble"]
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/exchange-rates", "--build-arg=JAR_FILE=build/libs/exchange-rates-1.0.0.jar", "."]
images: ["gcr.io/$PROJECT_ID/exchange-rates"]
