steps:
  - name: gradle:jdk11
    entrypoint: gradle
    args: ['build', '--no-daemon', '--parallel']

  - name: gcr.io/cloud-builders/docker
    args:
    - 'build'
    - '--tag=gcr.io/$PROJECT_ID/$REPO_NAME'
    - '--tag=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
    - '--build-arg=JAR_FILE=build/libs/exchange-rates-*.jar'
    - '.'

  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/$REPO_NAME'

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - 'run'
      - '--filename=kubernetes.yaml'
      - '--image=gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'
      - '--location=${_CLUSTER_ZONE}'
      - '--cluster=${_CLUSTER_NAME}'

images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME:$TAG_NAME'

substitutions:
  _CLUSTER_NAME: $PROJECT_ID
  _CLUSTER_ZONE: us-central1-c
  TAG_NAME: $SHORT_SHA

tags:
  - $REPO_NAME
