steps:
  - name: gradle:jdk8
    entrypoint: gradle
    args: ["assemble"]
    id: assemble-jar

  - name: gcr.io/cloud-builders/docker
    args:
    - "build"
    - '--tag=gcr.io/$PROJECT_ID/exchange-rates'
    - '--tag=gcr.io/$PROJECT_ID/exchange-rates:$SHORT_SHA'
    - "--build-arg=JAR_FILE=build/libs/exchange-rates-1.0.0.jar"
    - "."
    id: build-docker-image
    waitFor:
      - assemble-jar

  - name: gcr.io/cloud-builders/docker
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/exchange-rates'
    id: push-docker-image
    waitFor:
      - build-docker-image

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes.yaml
      - --image=gcr.io/$PROJECT_ID/exchange-rates:$SHORT_SHA
      - --location=us-central1-c
      - --cluster=my-first-cluster-1
    waitFor:
      - push-docker-image
