apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-rates-deployment
  labels:
    app: exchange-rates-api
spec: # replica set
  replicas: 1 # cantidad de pods
  selector:
    matchLabels:
      app: exchange-rates-api
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: # pod template
    metadata:
      labels:
        app: exchange-rates-api
    spec:
      containers: # docker container[i]
        - name: exchange-rates-container
          image: gcr.io/ezetarg-gke/exchange-rates
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-rates-service
spec:
  type: LoadBalancer # NodePort
  selector:
    app: exchange-rates-api
  ports:
    - protocol: TCP
      port: 8080 # external port 80
      targetPort: 8080 # pod port

